#!/bin/bash

if command -v python3 &>/dev/null; then
    python3 ./base/main/shellstart.py
    echo "[ ✓ ] Get!"
    python3 ./base/main/desktop.py
else
    echo "python isn't installed, please install it."
fi
